# Generated by Django 5.2.3 on 2025-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_policy',
            field=models.BooleanField(default=False),
        ),
    ]
